-
  name: vader:hallway
  filename: D:\Filmy\Filmy\Star wars\3.9) Łotr Jeden\3.9) Łotr Jeden.mkv
  srt: D:\Filmy\Filmy\Star wars\3.9) Łotr Jeden\rogue one.srt
  timestamp:
    - ['2:04:01', '2:04:37']
